name: Compress Images

on:
  push:
    paths:
      - 'static/**'

jobs:
  compress_devcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.API }}
          commit_message: "tinify devcard and converted to webp"
          commit_user_name: "STICKnoLOGIC-automation[bot]"
          commit_user_email: "johnaerial.azcune@sticknologic.is-a.dev"
