name: Compress Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'static/**'

jobs:
  compress_devcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: converting to webp
        run: |
          curl -o static/devcard.webp https://api.tinify.com/output/2xnsp7jn34e5 \
          --user api:${{ secrets.API }} \
          --header "Content-Type: application/json" \
          --data '{ "convert": { "type": "image/webp"} }' \
          --dump-header /dev/stdout \
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.API }}
          commit_message: "tinify devcard and converted to webp"
