name: Daily.dev (DevCard puller)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
 devcard_puller:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAS }}
      - name: getting devcard
        run: |
          curl -o static/devcard.png "https://api.daily.dev/devcards/v2/Q7zjcKv8tezBcFJWbq2KQ.png?type=wide"
          git config user.name "github-actions[bot]"
          git config user.email "bot.no_reply@sticknologic.is-a.dev"
          git add .
          git commit -m "chore: update DevCard"
          git push

