name: Daily.dev (DevCard puller)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
 devcard_puller:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAS }}
      - name: getting devcard
        uses: dailydotdev/action-devcard@3.2.0
        with:
          user_id: ${{ secrets.UID }}
          type: wide
          commit_message: "chore: update ${filename}"
      - name: resizing devcard
        uses: namoscato/action-tinify@1.4.0
        with:
          api_key: ${{ secrets.API }}
          commit_message: "tinify devcard"
