name: Daily.dev (DevCard puller)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
 devcard_puller:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAS }}
      - name: Setup cwebp
        run: |
          pwd
          sudo apt-get update --fix-missing
          sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.4-linux-x86-64.tar.gz
          tar xzvf libwebp-1.2.4-linux-x86-64.tar.gz
          cd libwebp-1.2.4-linux-x86-64/bin
          mv cwebp ${{ github.workspace }}
          cd ../..
          rm -rf libwebp-1.2.4-linux-x86-64
          rm -rf libwebp-1.2.4-linux-x86-64.tar.gz
          sudo mv cwebp /bin
          ls
      - name: getting devcard
        run: |
          curl --create-dirs -o static/devcard.png "https://api.daily.dev/devcards/v2/Q7zjcKv8tezBcFJWbq2KQ.png?type=wide"
          cd static
          cwebp -q 80 "devcard.png" -o "devcard.webp"
          rm -f **.png
          cd ..
          curl --create-dirs -o static/gh-streak.svg "https://github-readme-streak-stats-eight.vercel.app/?user=STICKnoLOGIC&theme=slateorange&type=svg"
          curl --create-dirs -o static/gh-stat.svg "https://github-readme-stats.vercel.app/api/top-langs?username=STICKnoLOGIC&show_icons=true&locale=en&layout=compact&theme=slateorange&type=svg"
          git config --global user.name "STICKnoLOGIC-automation[bot]"
          git config --global user.email "johnaerial.azcune@sticknologic.is-a.dev"
          git add .
          git commit -m "chore: fetch DevCard"
          git push

